name: Gosoline

on: [push]
jobs:

  test:
    name: Build + Test
    runs-on: ubuntu-18.04
    steps:

      - name: Set up Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Get dependencies
        run: go get -v -t -d ./...

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test ./...

      - name: Integration tests
        run: |
          sudo sysctl -p
          go test -p 1 --tags=integration  ./test/component_sns_sqs_test.go
          go test -p 1 --tags=integration  ./test/component_sns_sqs_test.go
          go test -p 1 --tags=integration  ./test/component_sns_sqs_test.go
          go test -p 1 --tags=integration  ./test/component_sns_sqs_test.go
          go test -p 1 --tags=integration  ./test/component_sns_sqs_test.go
